/**
 * Static image data — placeholder dataset using picsum.photos.
 *
 * Architecture note:
 * These images are served from picsum.photos for demonstration.
 * In production, replace src URLs with Synology NAS paths or a CDN.
 * The imageService.js abstraction layer handles source switching via
 * the IMAGE_SOURCE environment variable.
 *
 * Image fields:
 *   id        — unique identifier
 *   src       — image URL (currently picsum.photos, future: NAS)
 *   alt       — accessibility description
 *   category  — portfolio category slug
 *   width     — natural image width
 *   height    — natural image height
 *   featured  — show on home page portfolio preview
 *   title     — optional display title
 */

export const images = [
  // ── Weddings ──────────────────────────────────────────────
  {
    id: 1,
    src: 'https://picsum.photos/seed/w1/800/1067',
    alt: 'Bride and groom during ceremony',
    category: 'weddings',
    width: 800,
    height: 1067,
    featured: true,
    title: 'Garden Ceremony',
  },
  {
    id: 2,
    src: 'https://picsum.photos/seed/w2/1067/800',
    alt: 'Wedding reception golden hour',
    category: 'weddings',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Golden Hour',
  },
  {
    id: 3,
    src: 'https://picsum.photos/seed/w3/800/1067',
    alt: 'Couple first dance at reception',
    category: 'weddings',
    width: 800,
    height: 1067,
    featured: true,
    title: 'First Dance',
  },
  {
    id: 4,
    src: 'https://picsum.photos/seed/w4/900/900',
    alt: 'Wedding rings on floral arrangement',
    category: 'weddings',
    width: 900,
    height: 900,
    featured: false,
    title: 'The Rings',
  },
  {
    id: 5,
    src: 'https://picsum.photos/seed/w5/800/1067',
    alt: 'Bride portrait with veil',
    category: 'weddings',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Bridal Portrait',
  },
  {
    id: 6,
    src: 'https://picsum.photos/seed/w6/1067/800',
    alt: 'Wedding venue decoration',
    category: 'weddings',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Venue Details',
  },

  // ── Portraits ─────────────────────────────────────────────
  {
    id: 7,
    src: 'https://picsum.photos/seed/p1/800/1067',
    alt: 'Female portrait in natural light',
    category: 'portraits',
    width: 800,
    height: 1067,
    featured: true,
    title: 'Natural Light',
  },
  {
    id: 8,
    src: 'https://picsum.photos/seed/p2/800/1067',
    alt: 'Dramatic studio portrait',
    category: 'portraits',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Studio Session',
  },
  {
    id: 9,
    src: 'https://picsum.photos/seed/p3/1067/800',
    alt: 'Outdoor lifestyle portrait',
    category: 'portraits',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Outdoor',
  },
  {
    id: 10,
    src: 'https://picsum.photos/seed/p4/800/1067',
    alt: 'Portrait with soft bokeh background',
    category: 'portraits',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Bokeh Portrait',
  },
  {
    id: 11,
    src: 'https://picsum.photos/seed/p5/900/900',
    alt: 'Close up portrait with golden hour light',
    category: 'portraits',
    width: 900,
    height: 900,
    featured: false,
    title: 'Golden Hour',
  },

  // ── Couples ───────────────────────────────────────────────
  {
    id: 12,
    src: 'https://picsum.photos/seed/c1/1067/800',
    alt: 'Couple walking in autumn park',
    category: 'couples',
    width: 1067,
    height: 800,
    featured: true,
    title: 'Autumn Walk',
  },
  {
    id: 13,
    src: 'https://picsum.photos/seed/c2/800/1067',
    alt: 'Couple portrait at sunset',
    category: 'couples',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Sunset Session',
  },
  {
    id: 14,
    src: 'https://picsum.photos/seed/c3/800/1067',
    alt: 'Engagement session in the city',
    category: 'couples',
    width: 800,
    height: 1067,
    featured: false,
    title: 'City Engagement',
  },
  {
    id: 15,
    src: 'https://picsum.photos/seed/c4/1067/800',
    alt: 'Couple in a field of flowers',
    category: 'couples',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Wildflower Field',
  },
  {
    id: 16,
    src: 'https://picsum.photos/seed/c5/800/1067',
    alt: 'Intimate couple moment',
    category: 'couples',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Intimate Moment',
  },

  // ── Family ────────────────────────────────────────────────
  {
    id: 17,
    src: 'https://picsum.photos/seed/f1/1067/800',
    alt: 'Family portrait in the park',
    category: 'family',
    width: 1067,
    height: 800,
    featured: true,
    title: 'Park Session',
  },
  {
    id: 18,
    src: 'https://picsum.photos/seed/f2/800/1067',
    alt: 'Newborn photography session',
    category: 'family',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Newborn',
  },
  {
    id: 19,
    src: 'https://picsum.photos/seed/f3/1067/800',
    alt: 'Family on the beach at sunset',
    category: 'family',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Beach Sunset',
  },
  {
    id: 20,
    src: 'https://picsum.photos/seed/f4/800/1067',
    alt: 'Children playing outdoors',
    category: 'family',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Childhood',
  },
  {
    id: 21,
    src: 'https://picsum.photos/seed/f5/900/900',
    alt: 'Family holiday portrait',
    category: 'family',
    width: 900,
    height: 900,
    featured: false,
    title: 'Holiday Session',
  },

  // ── Events ────────────────────────────────────────────────
  {
    id: 22,
    src: 'https://picsum.photos/seed/e1/1067/800',
    alt: 'Corporate event photography',
    category: 'events',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Corporate Event',
  },
  {
    id: 23,
    src: 'https://picsum.photos/seed/e2/800/1067',
    alt: 'Birthday celebration',
    category: 'events',
    width: 800,
    height: 1067,
    featured: true,
    title: 'Celebration',
  },
  {
    id: 24,
    src: 'https://picsum.photos/seed/e3/1067/800',
    alt: 'Gala evening event',
    category: 'events',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Gala Evening',
  },
  {
    id: 25,
    src: 'https://picsum.photos/seed/e4/800/1067',
    alt: 'Art gallery opening night',
    category: 'events',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Gallery Opening',
  },
  {
    id: 26,
    src: 'https://picsum.photos/seed/e5/1067/800',
    alt: 'Outdoor festival photography',
    category: 'events',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Summer Festival',
  },

  // ── Real photos from @alina_vladyka ───────────────────────
  {
    id: 32,
    src: '/instagram/ig8.jpg',
    alt: 'Portrait session — woman in red with floating roses',
    category: 'portraits',
    width: 640,
    height: 853,
    featured: true,
    title: 'With Roses',
  },
  {
    id: 33,
    src: '/instagram/ig11.jpg',
    alt: 'Couples session at winter waterfall',
    category: 'couples',
    width: 640,
    height: 427,
    featured: true,
    title: 'Winter Waterfall',
  },
  {
    id: 34,
    src: '/instagram/ig12.jpg',
    alt: 'Newborn session — baby feet, first days',
    category: 'family',
    width: 640,
    height: 1136,
    featured: true,
    title: 'First Days',
  },
  {
    id: 35,
    src: '/instagram/ig10.jpg',
    alt: 'Lifestyle portrait — woman among the roses',
    category: 'lifestyle',
    width: 640,
    height: 427,
    featured: false,
    title: 'Among the Roses',
  },
  {
    id: 36,
    src: '/instagram/ig19.jpg',
    alt: 'Baby portrait — first year, learning to crawl',
    category: 'family',
    width: 640,
    height: 853,
    featured: true,
    title: 'First Year',
  },
  {
    id: 37,
    src: '/instagram/ig20.jpg',
    alt: 'Dramatic portrait in warm golden light',
    category: 'portraits',
    width: 640,
    height: 853,
    featured: true,
    title: 'Golden Light',
  },
  {
    id: 38,
    src: '/instagram/ig21.jpg',
    alt: "Valentine children session — girl's joy",
    category: 'family',
    width: 640,
    height: 853,
    featured: false,
    title: 'Valentine Joy',
  },
  {
    id: 39,
    src: '/instagram/ig22.jpg',
    alt: 'Photographer Alina Vladyka with Nikon camera, winter outdoor',
    category: 'lifestyle',
    width: 640,
    height: 853,
    featured: false,
    title: 'Behind the Lens',
  },
  {
    id: 40,
    src: '/instagram/ig9.jpg',
    alt: 'Rose decoration detail — soft bokeh',
    category: 'lifestyle',
    width: 311,
    height: 311,
    featured: false,
    title: 'Rose Detail',
  },
  {
    id: 41,
    src: '/instagram/ig13.jpg',
    alt: 'Photographer Alina Vladyka at cafe with camera',
    category: 'lifestyle',
    width: 311,
    height: 311,
    featured: false,
    title: 'At Work',
  },

  // ── Lifestyle ─────────────────────────────────────────────
  {
    id: 27,
    src: 'https://picsum.photos/seed/l1/800/1067',
    alt: 'Morning coffee lifestyle shoot',
    category: 'lifestyle',
    width: 800,
    height: 1067,
    featured: true,
    title: 'Morning Light',
  },
  {
    id: 28,
    src: 'https://picsum.photos/seed/l2/1067/800',
    alt: 'Urban lifestyle photography',
    category: 'lifestyle',
    width: 1067,
    height: 800,
    featured: false,
    title: 'City Life',
  },
  {
    id: 29,
    src: 'https://picsum.photos/seed/l3/800/1067',
    alt: 'Lifestyle portrait in natural setting',
    category: 'lifestyle',
    width: 800,
    height: 1067,
    featured: false,
    title: 'Everyday Beauty',
  },
  {
    id: 30,
    src: 'https://picsum.photos/seed/l4/900/900',
    alt: 'Creative lifestyle photography',
    category: 'lifestyle',
    width: 900,
    height: 900,
    featured: false,
    title: 'Creative Vision',
  },
  {
    id: 31,
    src: 'https://picsum.photos/seed/l5/1067/800',
    alt: 'Lifestyle travel photography',
    category: 'lifestyle',
    width: 1067,
    height: 800,
    featured: false,
    title: 'Wanderlust',
  },
];

export const categories = [
  { slug: 'all', label: 'All Work' },
  { slug: 'weddings', label: 'Weddings' },
  { slug: 'portraits', label: 'Portraits' },
  { slug: 'couples', label: 'Couples' },
  { slug: 'family', label: 'Family' },
  { slug: 'events', label: 'Events' },
  { slug: 'lifestyle', label: 'Lifestyle' },
];

// Instagram preview — real photos from @alina_vladyka, refreshed on each deploy
// (local copies in /public/instagram/ to avoid CDN expiry)
export const instagramPreviews = [
  { id: 'ig1', src: '/instagram/ig8.jpg',  alt: 'Portrait session by Alina Vladyka' },
  { id: 'ig2', src: '/instagram/ig19.jpg', alt: 'Family portrait by Alina Vladyka' },
  { id: 'ig3', src: '/instagram/ig11.jpg', alt: 'Couples session by Alina Vladyka' },
  { id: 'ig4', src: '/instagram/ig20.jpg', alt: 'Portrait by Alina Vladyka' },
  { id: 'ig5', src: '/instagram/ig12.jpg', alt: 'Newborn session by Alina Vladyka' },
  { id: 'ig6', src: '/instagram/ig21.jpg', alt: 'Children session by Alina Vladyka' },
  { id: 'ig7', src: '/instagram/ig9.jpg',  alt: 'Creative detail by Alina Vladyka' },
  { id: 'ig8', src: '/instagram/ig10.jpg', alt: 'Lifestyle shoot by Alina Vladyka' },
  { id: 'ig9', src: '/instagram/ig22.jpg', alt: 'Behind the lens by Alina Vladyka' },
];
